---
# Tarefas que serão executadas em todos os nós

- name: Copia o codigo do repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/tmp2/

- name: Rodar o discovery 
  shell: sh /tmp/tmp2/ansible-discovery-linux/discovery.sh

- name: Resgata o report do servidor remoto
  fetch:
    src: /tmp/discovery/
    dest: /tmp/
