---
# Tarefas que serão executadas em todos os nós

- name: Copia o codigo do repositorio
  git: 
    repo: {{ repository }} 
    dest: /tmp/
    clone: no
    update: no
- name: Rodar o discovery 
  command: sh /tmp/ansible-discovery-linux/discovery.sh

- name: Resgata o report do servidor remoto
  fetch:
    src: /tmp/discovery/
    dest: /tmp/
