---
# Tarefas que serão executadas em todos os nós

- name: Remover pasta manobra
    shell: "rm -rf /tmp/stage-discovery"
- name: Criar pasta manobra
    shell: "mkdir -p /tmp/stage-discovery/logs"

- name: Copia o codigo do repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/
    clone: yes
    update: yes

- name: Rodar o discovery 
  shell: sh /tmp/stage-discovery/discovery.sh > /tmp/stage-discovery/logs/{{ inventory_hostname }}.delivery.txt"

- name: Resgata o report do servidor remoto
  shell: "ls /tmp/stage-discovery/logs/{{ inventory_hostname }}.delivery.txt"



