---
# Tarefas que serão executadas em todos os nós

- name: Organizar workspace
  file:
   path: /tmp/stage-discovery
   state: absent

- name: Checkout de repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/
    clone: yes
    update: yes

- name: Checkout de repositorio
  file:
    path: /tmp/stage-discovery/discovery.sh
    mode: 0755
