---
# Tarefas que serão executadas em todos os nós
- name: Remover area manobra
  file:
    path: /tmp/stage-discovery
    state: absent
    
    - shell: "rm -rf /tmp/stage-discovery"

- name: Cria a area manobra
  file:
    path: /tmp/stage-discovery
        state: directory

- name: Cria a area manobra logs
  file:
    path: /tmp/stage-discovery/logs/
        state: directory

- name: Copia o codigo do repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/
    clone: yes
    update: yes

- name: Rodar o discovery 
  shell: sh /tmp/stage-discovery/discovery.sh > /tmp/stage-discovery/logs/{{ inventory_hostname }}.delivery.txt"

- name: Resgata o report do servidor remoto
  shell: "ls /tmp/stage-discovery/logs/{{ inventory_hostname }}.delivery.txt"



