---
# Tarefas que serão executadas em todos os nós

- name: Copia o codigo do repositorio
  git: repo={{ repository }} dest=/tmp/temp/

- name: Rodar o discovery 
  command: /tmp/temp/ansible-discovery-linux/discovery.sh

- name: Resgata o report do servidor remoto
  fetch:
    src: /tmp/*.discovery.txt
    dest: /tmp/
