---
# Tarefas que serão executadas em todos os nós

- name: Remover workspace
  file:
   path: /tmp/stage-discovery
   state: absent

- name: Checkout de repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/
    clone: yes
    update: yes
