---
# Tarefas que serão executadas em todos os nós

- name: Remover workspace
  shell: rm -rf /tmp/stage-discovery
  args:
    executable: /bin/bash

- name: Copia o codigo do repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/
    clone: yes
    update: yes
