---
# Tarefas que serão executadas em todos os nós
- name: Remover area manobra
  file:
    path: /tmp/stage-discovery
    state: absent

- name: Cria a area manobra
  file:
    path: /tmp/stage-discovery/
    state: directory

- name: Cria a area manobra logs
  file:
    path: /tmp/stage-discovery/logs/
    state: directory

- name: Copia o codigo do repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/

- name: Rodar o discovery 
  shell: sh /tmp/stage-discovery/discovery.sh

- name: Resgata o report do servidor remoto
  shell: (cd /tmp/stage-discovery/logs; find . -maxdepth 1 -type f) | cut -d'/' -f2
    register: files_to_copy
  fetch: src=/tmp/stage-discovery/logs/{{ item }} dest=/tmp/
    with_items: files_to_copy.stdout_lines
