---
# Playbook de discovery

- name: Organizar workspace
  file:
   path: /tmp/stage-discovery
   state: absent


- name: Checkout de repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/
    clone: yes
    update: yes


- name: Garantir prerrogativas de execucao
  file:
    path: /tmp/stage-discovery/master.sh
    mode: 0755


- name: Executar procedimentos
  shell: /tmp/stage-discovery/master.sh >> /tmp/stage-discovery/{{ ansible_hostname }}.discovery.txt


- name: Coletar arquivo e finalizar processo
  fetch:
    src: /tmp/stage-discovery/{{ ansible_hostname }}.discovery.txt
    dest: {{ reports_path }}
