---
# Tarefas que serão executadas em todos os nós
- name: Remover area manobra
  file:
    path: /tmp/stage-discovery
    state: absent

- name: Cria a area manobra
  file:
    path: /tmp/stage-discovery/
    state: directory

- name: Copia o codigo do repositorio
  git: 
    repo: "{{ repository }}"
    dest: /tmp/stage-discovery/

- name: Rodar o discovery 
  shell: sh /tmp/stage-discovery/discovery.sh

- name: Resgata o report do servidor remoto
  fetch:
    src: /tmp/stage-discovery/
    dest: /tmp/
